trigger: 
- develop
- release/*
- hotfix/*

variables:
  - group: CIAutomation
  # Access token for the git repository. Used by the git tag task.
  - name: system_accesstoken
    value: $(System.AccessToken)
  # Include shared variables
  - template: shared-variables.yml

resources:
  repositories:
    - repository: ciTemplates # Id of the repository used to reference to in this script
      type: git
      name: common-ci # Name of the actual repository
      
stages:
- stage: Build_Packages
  displayName: Build Packages
  jobs:
  - template: shared-git-version-job.yml@ciTemplates
    parameters:
      imageName: $(linuxImage)

  - template: shared-build-plugin-job.yml
    parameters:
      # Development buildType parameter indicates that build and test 
      # stage will use submodule references for pipeline dependencies.
      buildType: 'Development'
      imageName: $(linuxImage)

  - template: shared-git-tag-job.yml@ciTemplates
    parameters:
      imageName: $(linuxImage)
      jobDependencies: [Versioning,Build_Plugin]
